# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshang', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logins',
            field=models.IntegerField(default=0),
        ),
    ]
