# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letshang', '0004_userprofile_logins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='logins',
            new_name='activity_count',
        ),
    ]
