# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letshang', '0005_auto_20171205_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=b'https://cdn.pixabay.com/photo/2012/04/26/19/43/profile-42914_960_720.png', upload_to=b'photos'),
        ),
    ]
