# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letshang', '0007_auto_20171206_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
    ]
