# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('eat', 'I want to eat!'), ('study', 'I want to study!'), ('workout', 'I want to workout!')], default='eat', max_length=10)),
            ],
        ),
    ]
